# Generated by Django 4.0.4 on 2023-02-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_album', '0005_diary_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='名前')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
        migrations.AlterField(
            model_name='diary',
            name='title',
            field=models.CharField(default='no title', max_length=50, verbose_name='タイトル'),
        ),
        migrations.AddField(
            model_name='diary',
            name='tags',
            field=models.ManyToManyField(blank=True, to='travel_album.tag', verbose_name='タグ'),
        ),
    ]
