# Generated by Django 4.0.4 on 2023-02-20 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_album', '0006_tag_alter_diary_title_diary_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='is_publish',
            field=models.BooleanField(default=False, verbose_name='公開するか'),
        ),
    ]
