# Generated by Django 4.0.4 on 2023-03-20 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_album', '0007_diary_is_publish'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_information',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to='travel_album.diary', verbose_name='いいねした投稿'),
        ),
    ]
