# Generated by Django 4.0.4 on 2023-04-05 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_album', '0007_diary_is_publish'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_user_information_like_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_information',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='followed_by', to=settings.AUTH_USER_MODEL, verbose_name='フォロー中'),
        ),
        migrations.AlterField(
            model_name='user_information',
            name='like_post',
            field=models.ManyToManyField(blank=True, related_name='liked_by', to='travel_album.diary', verbose_name='いいねした投稿'),
        ),
    ]
